version: '3'
services:
  eureka-server:
    image: eureka-server-image
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - my-network

  ms-gestion-user:
    image: ms-gestion-utilisateur-image
    container_name: ms-gestion-utilisateur-container
    ports:
      - "8888:8888"
    networks:
      - my-network
    depends_on:
      - eureka-server

  ms-review:
    image: ms-review-image
    container_name: ms-review-container
    ports:
      - "5000:5000"
    networks:
      - my-network
    depends_on:
      - eureka-server

networks:
  my-network:
