version: '3'
services:
  eureka-server:
    image: eureka-server-image
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - my-network

  ms-gestion-user:
    image: ms-gestion-utilisateur-image
    container_name: ms-gestion-utilisateur-container
    ports:
      - "8888:8888"
    networks:
      - my-network
    depends_on:
      - eureka-server

  ms-livre:
    image: ms-livre-image
    container_name: ms-livre-container
    ports:
      - "8686:8686"
    networks:
      - my-network
    depends_on:
      - eureka-server

  #ms-emprunt:
  #  container_name: ms-emprunt-container
  #  ports:
  #    - "8280:8280"
  #  environment:
  #    - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/empruntes?createDatabaseIfNotExist=true&userSSL=false&max_allowed_packet=15728640
  #    - SPRING_DATASOURCE_USERNAME=root
  #    - SPRING_DATASOURCE_PASSWORD=
  #  image: ms-emprunt-image
  #  restart: unless-stopped
  #  depends_on:
  #    - eureka-server
  #    - db-mysql

  db-mysql:
      image: "mysql:latest"
      container_name: db-mysql  
      environment:
        - MYSQL_ROOT_PASSWORD=root
        #- MYSQL_DATABASE=job
      ports:
        - "3307:330"
      restart: unless-stopped  

  ms-review:
    image: ms-review-image
    container_name: ms-review-container
    ports:
      - "5000:5000"
    networks:
      - my-network
    depends_on:
      - eureka-server

networks:
  my-network:
